Add mate::Promise
zcbenz/native-mate pull request #23
Opened 2018-03-28 00:33 UTC by MarshallOfSound

This is just so we can start looking at native promisification in Electron 👍

2018-03-28 00:34 UTC, MarshallOfSound commented on native_mate/dictionary.cc
> -  return Dictionary(isolate, v8::Object::New(isolate));;
Yeah this bugged me 😆

2018-03-28 00:34 UTC, MarshallOfSound commented on native_mate/promise.h
> +  // TODO(MarshallOfSound): Implement FromV8 to allow promise chaining
We don't have a use case for this yet and it's actually quite a hard thing to do, so gonna leave it out till we need to take in promises (don't see why we would yet)

2018-04-02 05:36 UTC, zcbenz requested changes

2018-04-02 05:36 UTC, zcbenz commented on native_mate/promise.h
> +  static Promise Create();
The `Create` methods are unnecessary.

2018-04-02 15:16 UTC, alexeykuzmin commented on native_mate/promise.cc
> +    : isolate_(NULL) {
`nullptr` maybe?

2018-04-02 15:23 UTC, alexeykuzmin commented on native_mate/promise.cc
> +                                                  Promise val) {
Indentation is a bit off here.

2018-04-02 15:26 UTC, alexeykuzmin commented on native_mate_files.gypi
> +      'native_mate/promise.cc',
The list seems to be sorted alphabetically.

2018-04-11 19:27 UTC, YurySolovyov commented
Closes/Refs #20 ?

2018-04-12 02:54 UTC, MarshallOfSound commented
@alexeykuzmin @zcbenz Updated as per feedback 👍

2018-04-13 14:51 UTC, alexeykuzmin approved these changes

2018-04-16 10:18 UTC, merged