Ensure all promises are persisted on the heap
zcbenz/native-mate pull request #32
Opened 2018-04-16 11:41 UTC by MarshallOfSound

Unlike dictionaries, there is no use case for a limited lifetime promise. The lifetime of promises can extend the lifetime of local scopes and normally have to.

2018-04-16 13:55 UTC, alexeykuzmin commented
@MarshallOfSound please rebase on the latest `master` to fix the CI jobs.

2018-04-16 16:15 UTC, codebytere approved these changes

2018-04-17 06:43 UTC, zcbenz requested changes

2018-04-17 06:43 UTC, zcbenz commented on native_mate/promise.h
>    static Promise Create();
The `Create` methods can be deleted.

2018-04-17 06:43 UTC, zcbenz commented on native_mate/promise.h
> +  scoped_refptr<RefCountedPersistent<v8::Promise::Resolver>> handle_;
We should use `v8::Global` here. `RefCountedPersistent` is only for the cases when we want to copy persistent handles, the `Promise` just be a movable type.

2018-05-30 14:23 UTC, closed without merging